In [ ]:
import pandas as pd
import numpy as np

In [ ]:
class MultipleLinearRegression:
    def __init__(self):
        self.coefficients = None
        #constructor to the class which set coefficients to none
    def fit(self, X, y):
        # Add a column of ones to the design matrix X
        X_design = [[1] + row for row in X] #adding ones column to calculate b0 value
        n = len(X_design[0])#finding the no.of columns
        m = len(y)#finding no.of rows of dependent variable
        
        # Initialize the normal equations matrix A and the right-hand side vector b
        A = [[0] * n for i in range(n)]#an empty array with shape as n*n(2D)
        b = [0] * n #1D array
        
        # Fill in the elements of A and b
        for i in range(n):
            for j in range(n):
                for k in range(m):
                    A[i][j] += X_design[k][i] * X_design[k][j]
            for k in range(m):
                b[i] += X_design[k][i] * y[k]
        
        # Solve the system of linear equations Ax = b using Gaussian elimination
        for i in range(n):
            for j in range(i + 1, n):
                factor = A[j][i] / A[i][i]
                for k in range(i + 1, n):
                    A[j][k] -= factor * A[i][k]
                b[j] -= factor * b[i]
                
        self.coefficients = [0] * n
        for i in range(n - 1, -1, -1):
            for j in range(i + 1, n):
                b[i] -= A[i][j] * self.coefficients[j]
            self.coefficients[i] = b[i] / A[i][i]

    def predict(self, X):
        # Add a column of ones to the design matrix X
        X_design = [[1] + row for row in X]
        y_pred = [sum([X_design[i][j] * self.coefficients[j] for j in range(len(self.coefficients))]) for i in range(len(X_design))]
        return y_pred




In [ ]:
df=pd.read_csv("/content/kc_house_data.csv")
x =df[["bathrooms",	"sqft_living",	"grade",	"sqft_above",	"sqft_living15"]]
y = df[["price"]]

In [ ]:
ratio = 0.80
 
total_rows = df.shape[0]
train_size = int(total_rows*ratio)
 
# Split data into test and train
x_train =(x[0:train_size].values)

y_train=(y[0:train_size].values)
x_test =(x[train_size:].values)

y_test =(y[train_size:].values)

In [ ]:
mlr = MultipleLinearRegression()

# Fit the model to the data
mlr.fit(x_train, y_train)

# Make predictions on the test data
y_pred = mlr.predict(x_test)

In [ ]:
y_pred

[array([586010.48122731]),
 array([586010.48122731]),
 array([334719.54912743]),
 array([314866.58429068]),
 array([742222.38528987]),
 array([505555.68017519]),
 array([393737.55177135]),
 array([278419.48212452]),
 array([557845.3284318]),
 array([236242.3327538]),
 array([442010.94249466]),
 array([541083.87176764]),
 array([296929.77258968]),
 array([251680.95093063]),
 array([360392.11978179]),
 array([674672.10087595]),
 array([611536.1563882]),
 array([504867.95236853]),
 array([536646.69520892]),
 array([219250.64388291]),
 array([588352.96204885]),
 array([238094.85997379]),
 array([1270031.48670889]),
 array([356916.58488928]),
 array([177801.98683974]),
 array([381371.07057613]),
 array([545517.11925158]),
 array([378500.51895842]),
 array([455897.18459681]),
 array([212215.8409395]),
 array([634258.35241291]),
 array([333197.3132221]),
 array([635044.25101316]),
 array([698014.12094975]),
 array([890707.99379622]),
 array([591536.83332686]),
 array([230263.85188191]),
 arra

In [ ]:
y_test

array([[380000.],
       [624900.],
       [379770.],
       ...,
       [402101.],
       [400000.],
       [325000.]])